
default:

install:
	install -d "$(DESTDIR)/usr/share/openscada/profiles"
	install -d "$(DESTDIR)/usr/share/openscada/p2"
	
	install -d "$(DESTDIR)/usr/bin"
	install src/bin/* "$(DESTDIR)/usr/bin"

.PHONY: default install
