<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="common"
    nsURI="http://openscada.org/Configurator/Modules/Common" nsPrefix="common">
  <eClassifiers xsi:type="ecore:EClass" name="FileModule" abstract="true" interface="true"
      eSuperTypes="platform:/plugin/org.openscada.configurator.model/model/configurator.ecore#//Module">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eSubpackages name="network" nsURI="http://openscada.org/Configurator/Modules/Common/Network"
      nsPrefix="network">
    <eClassifiers xsi:type="ecore:EClass" name="NetworkModule" eSuperTypes="platform:/plugin/org.openscada.configurator.model/model/configurator.ecore#//Module">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="networkFile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral=""/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefix" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="scripts" nsURI="http://openscada.org/Configurator/Modules/Common/Scripts"
      nsPrefix="scripts">
    <eClassifiers xsi:type="ecore:EClass" name="ScriptsModule" eSuperTypes="platform:/plugin/org.openscada.configurator.model/model/configurator.ecore#//Module">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="scriptsFile" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LegacyFormulaModule" eSuperTypes="platform:/plugin/org.openscada.configurator.model/model/configurator.ecore#//Module">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="formulaFile" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ScriptsMonitorModule" eSuperTypes="#//FileModule"/>
  </eSubpackages>
  <eSubpackages name="processing" nsURI="http://openscada.org/Configurator/Modules/Common/Processing"
      nsPrefix="processing">
    <eClassifiers xsi:type="ecore:EClass" name="ImportModule" eSuperTypes="platform:/plugin/org.openscada.configurator.model/model/configurator.ecore#//Module #//FileModule"/>
    <eClassifiers xsi:type="ecore:EClass" name="OverrideListModule" eSuperTypes="#//FileModule"/>
    <eClassifiers xsi:type="ecore:EClass" name="ImportListModule" eSuperTypes="#//FileModule"/>
    <eClassifiers xsi:type="ecore:EClass" name="ScriptOverrides" eSuperTypes="#//FileModule"/>
    <eClassifiers xsi:type="ecore:EClass" name="RemoveInactive" eSuperTypes="platform:/plugin/org.openscada.configurator.model/model/configurator.ecore#//Module"/>
  </eSubpackages>
  <eSubpackages name="summary" nsURI="http://openscada.org/Configurator/Modules/Common/Summary"
      nsPrefix="summary">
    <eClassifiers xsi:type="ecore:EClass" name="SummaryFileLoader" eSuperTypes="#//FileModule">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="requiredItems" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="2"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GenerateSummaries" eSuperTypes="platform:/plugin/org.openscada.configurator.model/model/configurator.ecore#//Module">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="requiredItems" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="2"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="suffix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="main" nsURI="http://openscada.org/Configurator/Modules/Common/Main"
      nsPrefix="main">
    <eClassifiers xsi:type="ecore:EClass" name="MainLoader" eSuperTypes="platform:/plugin/org.openscada.configurator.model/model/configurator.ecore#//Module">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="file" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="marker" nsURI="http://openscada.org/Configurator/Modules/Common/Marker"
      nsPrefix="marker">
    <eClassifiers xsi:type="ecore:EClass" name="HierarchyMarkerGenerator" eSuperTypes="platform:/plugin/org.openscada.configurator.model/model/configurator.ecore#//Module">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="markerName" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="markers" upperBound="-1"
          eType="#//marker/Marker" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Marker">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HierarchyBlockGenerator" eSuperTypes="platform:/plugin/org.openscada.configurator.model/model/configurator.ecore#//Module"/>
  </eSubpackages>
</ecore:EPackage>
