<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="common"
    nsURI="http://openscada.org/Configurator/Modules/Common" nsPrefix="common">
  <eSubpackages name="network" nsURI="http://openscada.org/Configurator/Modules/Common/Network"
      nsPrefix="network">
    <eClassifiers xsi:type="ecore:EClass" name="NetworkModule" eSuperTypes="platform:/plugin/org.openscada.configurator.model/model/configurator.ecore#//Module">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="networkFile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral=""/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefix" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
